# Generated: references in Krieg's class mods that point at Borderlands 2's GD_ClassMods /
# GD_ItemGrades objects, which the Pre-Sequel renamed to GD_Cork_ClassMods / GD_Cork_ItemGrades.
# (object path, property path, Pre-Sequel object path)
CLASSMOD_REFS = (
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho', ('BaseDefinition',), 'GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_AllParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Blister', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Blister', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Blister', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Blister', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Blister', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Blister', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Blister', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Blister', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Crunch', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Crunch', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Crunch', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Crunch', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Crunch', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Crunch', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Crunch', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Crunch', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Crunch', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Meat', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Meat', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Meat', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Meat', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Meat', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Meat', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Meat', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Meat', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Reaper', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Reaper', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Reaper', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Reaper', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Reaper', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Reaper', ('AttributeSlotEffects', 0, 'ConstraintAttribute'), 'GD_Cork_ClassMods.Misc.Att_TeamConstraint'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Reaper', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Reaper', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Reaper', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Sickle', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Sickle', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Sickle', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Sickle', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Sickle', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Sickle', ('AttributeSlotEffects', 0, 'ConstraintAttribute'), 'GD_Cork_ClassMods.Misc.Att_TeamConstraint'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Sickle', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Sickle', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Sickle', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Sickle', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Slab', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Slab', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Slab', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Slab', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Slab', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Slab', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Slab', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Slab', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Toast', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Toast', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Toast', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Toast', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Toast', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Toast', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Strong'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Toast', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Toast', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Toast', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Toast', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Torch', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Torch', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Torch', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Torch', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Torch', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Torch', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Strong'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Torch', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Torch', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Torch', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Wound', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Wound', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Wound', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Wound', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Wound', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Wound', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Wound', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Wound', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Weak'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Weak'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('AttributeSlotEffects', 5, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('AttributeSlotEffects', 6, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('AttributeSlotEffects', 7, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_LengendaryPsycho', ('AttributeSlotEffects', 8, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Weak'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Weak'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('AttributeSlotEffects', 5, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('AttributeSlotEffects', 6, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.A_Item_Lilac.ClassMod_Psycho_Z_SlayerOfTerramorphous', ('AttributeSlotEffects', 7, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_01_Common.PartList', ('AlphaPartData', 'WeightedParts', 0, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_NoSkill'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_02_Uncommon.PartList', ('AlphaPartData', 'WeightedParts', 0, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS1'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_02_Uncommon.PartList', ('AlphaPartData', 'WeightedParts', 1, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS2'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_02_Uncommon.PartList', ('AlphaPartData', 'WeightedParts', 2, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS3'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_03_Rare.PartList', ('AlphaPartData', 'WeightedParts', 0, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS1_BS2'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_03_Rare.PartList', ('AlphaPartData', 'WeightedParts', 1, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS1_BS3'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_03_Rare.PartList', ('AlphaPartData', 'WeightedParts', 2, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS2_BS1'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_03_Rare.PartList', ('AlphaPartData', 'WeightedParts', 3, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS2_BS3'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_03_Rare.PartList', ('AlphaPartData', 'WeightedParts', 4, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS3_BS1'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_03_Rare.PartList', ('AlphaPartData', 'WeightedParts', 5, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS3_BS2'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_04_VeryRare.PartList', ('AlphaPartData', 'WeightedParts', 0, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS1_BS2_CS3'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_04_VeryRare.PartList', ('AlphaPartData', 'WeightedParts', 1, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS2_BS1_CS3'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_04_VeryRare.PartList', ('AlphaPartData', 'WeightedParts', 2, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS3_BS1_CS2'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_04_VeryRare.PartList', ('AlphaPartData', 'WeightedParts', 3, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS1_BS2_-CS3'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_04_VeryRare.PartList', ('AlphaPartData', 'WeightedParts', 4, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS1_-BS2_CS3'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_04_VeryRare.PartList', ('AlphaPartData', 'WeightedParts', 5, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS2_BS1_-CS3'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_04_VeryRare.PartList', ('AlphaPartData', 'WeightedParts', 6, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS2_-BS1_CS3'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_04_VeryRare.PartList', ('AlphaPartData', 'WeightedParts', 7, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS3_BS1_-CS2'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_04_VeryRare.PartList', ('AlphaPartData', 'WeightedParts', 8, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_AS3_-BS1_CS2'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_05_Legendary.PartList', ('AlphaPartData', 'WeightedParts', 0, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_Legendary'),
    ('GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_06_SlayerOfTerramorphous.PartList', ('AlphaPartData', 'WeightedParts', 0, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_Legendary'),
    ('GD_Lobelia_ItemGrades.ClassMods.BalDef_ClassMod_Lobelia_Psycho_05_Legendary', ('BaseDefinition',), 'GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_AllParts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('AttributeSlotEffects', 0, 'ConstraintAttribute'), 'GD_Cork_ClassMods.Misc.Att_TeamConstraint'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Reaper', ('AttributeSlotEffects', 5, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('AttributeSlotEffects', 0, 'ConstraintAttribute'), 'GD_Cork_ClassMods.Misc.Att_TeamConstraint'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Sickle', ('AttributeSlotEffects', 5, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Strong'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ClassMods.A_Item_Psycho.ClassMod_Psycho_Legendary_Torch', ('AttributeSlotEffects', 5, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Lobelia_ItemGrades.ClassMods.BalDef_ClassMod_Lobelia_Psycho_05_Legendary.PartList', ('AlphaPartData', 'WeightedParts', 0, 'Part'), 'GD_Cork_ClassMods.Specialization.Spec_Legendary'),
    ('GD_Aster_ItemGrades.ClassMods.BalDef_ClassMod_Aster_Psycho', ('BaseDefinition',), 'GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_AllParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_Barbarian', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_Barbarian', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_Barbarian', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_Barbarian', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_Barbarian', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_Barbarian', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_Barbarian', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_Barbarian', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_Barbarian', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CE', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CE', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CE', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CE', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CE', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CE', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CE', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium_Negative'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CE', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CE', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CE', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CG', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CG', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CG', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CG', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CG', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CG', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CG', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium_Negative'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CG', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CG', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CG', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CN', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CN', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CN', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CN', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CN', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CN', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CN', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium_Negative'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CN', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CN', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_CN', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LE', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LE', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LE', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LE', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LE', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LE', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LE', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium_Negative'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LE', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LE', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LE', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LG', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LG', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LG', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LG', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LG', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LG', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LG', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium_Negative'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LG', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LG', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LG', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LN', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LN', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LN', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LN', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LN', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LN', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LN', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium_Negative'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LN', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LN', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_LN', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NE', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NE', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NE', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NE', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NE', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NE', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NE', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NE', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NE', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NE', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NG', ('TitleList', 0), 'GD_Cork_ClassMods.Title.Title_ClassMod'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NG', ('AlphaParts',), 'GD_Cork_ClassMods.Specialization.Z_PartsList_SpecializationParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NG', ('BetaParts',), 'GD_Cork_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NG', ('GammaParts',), 'GD_Cork_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NG', ('MaterialParts',), 'GD_Cork_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NG', ('AttributeSlotEffects', 0, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NG', ('AttributeSlotEffects', 1, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_StatBonus_Medium'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NG', ('AttributeSlotEffects', 2, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NG', ('AttributeSlotEffects', 3, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
    ('GD_Aster_ClassMods.A_Item_Psycho.ClassMod_Barbarian_NG', ('AttributeSlotEffects', 4, 'BaseModifierValue', 'InitializationDefinition'), 'GD_Cork_ClassMods.Misc.Init_BaseSkillPointCalculation'),
)
