"""Object paths in Krieg's packages, generated offline from the DLC files."""

MATERIAL_INSTANCES = (
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho001",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho002",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho003",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho004",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho005",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho006",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho007",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho008",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho009",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho010",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho011",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho012",
    "CD_Heads_Psycho_Lilac.Materials.Mati_PsychoDLC1",
    "CD_Heads_Psycho_Lilac.Materials.Mati_PsychoDLC3",
    "CD_Heads_Psycho_Lilac.Materials.Mati_PsychoJack",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho_DLC2",
    "CD_Heads_Psycho_Lilac.Materials.Mati_Psycho_MC",
    "CD_Skins_Psycho_Lilac.Mati_BanditA_Body",
    "CD_Skins_Psycho_Lilac.Mati_BanditA_Head",
    "CD_Skins_Psycho_Lilac.Mati_BanditB_Body",
    "CD_Skins_Psycho_Lilac.Mati_BanditB_Head",
    "CD_Skins_Psycho_Lilac.Mati_BanditC_Body",
    "CD_Skins_Psycho_Lilac.Mati_BanditC_Head",
    "CD_Skins_Psycho_Lilac.Mati_BlackA_Body",
    "CD_Skins_Psycho_Lilac.Mati_BlackA_Head",
    "CD_Skins_Psycho_Lilac.Mati_BlueA_Body",
    "CD_Skins_Psycho_Lilac.Mati_BlueA_Head",
    "CD_Skins_Psycho_Lilac.Mati_BlueB_Body",
    "CD_Skins_Psycho_Lilac.Mati_BlueB_Head",
    "CD_Skins_Psycho_Lilac.Mati_BlueC_Body",
    "CD_Skins_Psycho_Lilac.Mati_BlueC_Head",
    "CD_Skins_Psycho_Lilac.Mati_BlueD_Body",
    "CD_Skins_Psycho_Lilac.Mati_BlueD_Head",
    "CD_Skins_Psycho_Lilac.Mati_BlueE_Body",
    "CD_Skins_Psycho_Lilac.Mati_BlueE_Head",
    "CD_Skins_Psycho_Lilac.Mati_BlueF_Body",
    "CD_Skins_Psycho_Lilac.Mati_BlueF_Head",
    "CD_Skins_Psycho_Lilac.Mati_BlueG_Body",
    "CD_Skins_Psycho_Lilac.Mati_BlueG_Head",
    "CD_Skins_Psycho_Lilac.Mati_BlueH_Body",
    "CD_Skins_Psycho_Lilac.Mati_BlueH_Head",
    "CD_Skins_Psycho_Lilac.Mati_CyanA_Body",
    "CD_Skins_Psycho_Lilac.Mati_CyanA_Head",
    "CD_Skins_Psycho_Lilac.Mati_CyanB_Body",
    "CD_Skins_Psycho_Lilac.Mati_CyanB_Head",
    "CD_Skins_Psycho_Lilac.Mati_CyanC_Body",
    "CD_Skins_Psycho_Lilac.Mati_CyanC_Head",
    "CD_Skins_Psycho_Lilac.Mati_CyanD_Body",
    "CD_Skins_Psycho_Lilac.Mati_CyanD_Head",
    "CD_Skins_Psycho_Lilac.Mati_CyanE_Body",
    "CD_Skins_Psycho_Lilac.Mati_CyanE_Head",
    "CD_Skins_Psycho_Lilac.Mati_CyanF_Body",
    "CD_Skins_Psycho_Lilac.Mati_CyanF_Head",
    "CD_Skins_Psycho_Lilac.Mati_CyanG_Body",
    "CD_Skins_Psycho_Lilac.Mati_CyanG_Head",
    "CD_Skins_Psycho_Lilac.Mati_CyanH_Body",
    "CD_Skins_Psycho_Lilac.Mati_CyanH_Head",
    "CD_Skins_Psycho_Lilac.Mati_DahlA_Body",
    "CD_Skins_Psycho_Lilac.Mati_DahlA_Head",
    "CD_Skins_Psycho_Lilac.Mati_DahlB_Body",
    "CD_Skins_Psycho_Lilac.Mati_DahlB_Head",
    "CD_Skins_Psycho_Lilac.Mati_DahlC_Body",
    "CD_Skins_Psycho_Lilac.Mati_DahlC_Head",
    "CD_Skins_Psycho_Lilac.Mati_Default_Body",
    "CD_Skins_Psycho_Lilac.Mati_Default_Head",
    "CD_Skins_Psycho_Lilac.Mati_Gearbox_Body",
    "CD_Skins_Psycho_Lilac.Mati_Gearbox_Head",
    "CD_Skins_Psycho_Lilac.Mati_GrayA_Body",
    "CD_Skins_Psycho_Lilac.Mati_GrayA_Head",
    "CD_Skins_Psycho_Lilac.Mati_GreenA_Body",
    "CD_Skins_Psycho_Lilac.Mati_GreenA_Head",
    "CD_Skins_Psycho_Lilac.Mati_GreenB_Body",
    "CD_Skins_Psycho_Lilac.Mati_GreenB_Head",
    "CD_Skins_Psycho_Lilac.Mati_GreenC_Body",
    "CD_Skins_Psycho_Lilac.Mati_GreenC_Head",
    "CD_Skins_Psycho_Lilac.Mati_GreenD_Body",
    "CD_Skins_Psycho_Lilac.Mati_GreenD_Head",
    "CD_Skins_Psycho_Lilac.Mati_GreenE_Body",
    "CD_Skins_Psycho_Lilac.Mati_GreenE_Head",
    "CD_Skins_Psycho_Lilac.Mati_GreenF_Body",
    "CD_Skins_Psycho_Lilac.Mati_GreenF_Head",
    "CD_Skins_Psycho_Lilac.Mati_GreenG_Body",
    "CD_Skins_Psycho_Lilac.Mati_GreenG_Head",
    "CD_Skins_Psycho_Lilac.Mati_GreenH_Body",
    "CD_Skins_Psycho_Lilac.Mati_GreenH_Head",
    "CD_Skins_Psycho_Lilac.Mati_HyperionA_Body",
    "CD_Skins_Psycho_Lilac.Mati_HyperionA_Head",
    "CD_Skins_Psycho_Lilac.Mati_HyperionB_Body",
    "CD_Skins_Psycho_Lilac.Mati_HyperionB_Head",
    "CD_Skins_Psycho_Lilac.Mati_HyperionC_Body",
    "CD_Skins_Psycho_Lilac.Mati_HyperionC_Head",
    "CD_Skins_Psycho_Lilac.Mati_JakobsA_Body",
    "CD_Skins_Psycho_Lilac.Mati_JakobsA_Head",
    "CD_Skins_Psycho_Lilac.Mati_JakobsB_Body",
    "CD_Skins_Psycho_Lilac.Mati_JakobsB_Head",
    "CD_Skins_Psycho_Lilac.Mati_JakobsC_Body",
    "CD_Skins_Psycho_Lilac.Mati_JakobsC_Head",
    "CD_Skins_Psycho_Lilac.Mati_MaliwanA_Body",
    "CD_Skins_Psycho_Lilac.Mati_MaliwanA_Head",
    "CD_Skins_Psycho_Lilac.Mati_MaliwanB_Body",
    "CD_Skins_Psycho_Lilac.Mati_MaliwanB_Head",
    "CD_Skins_Psycho_Lilac.Mati_MaliwanC_Body",
    "CD_Skins_Psycho_Lilac.Mati_MaliwanC_Head",
    "CD_Skins_Psycho_Lilac.Mati_Minecraft_Body",
    "CD_Skins_Psycho_Lilac.Mati_Minecraft_Head",
    "CD_Skins_Psycho_Lilac.Mati_OrangeA_Body",
    "CD_Skins_Psycho_Lilac.Mati_OrangeA_Head",
    "CD_Skins_Psycho_Lilac.Mati_OrangeB_Body",
    "CD_Skins_Psycho_Lilac.Mati_OrangeB_Head",
    "CD_Skins_Psycho_Lilac.Mati_OrangeC_Body",
    "CD_Skins_Psycho_Lilac.Mati_OrangeC_Head",
    "CD_Skins_Psycho_Lilac.Mati_OrangeD_Body",
    "CD_Skins_Psycho_Lilac.Mati_OrangeD_Head",
    "CD_Skins_Psycho_Lilac.Mati_OrangeE_Body",
    "CD_Skins_Psycho_Lilac.Mati_OrangeE_Head",
    "CD_Skins_Psycho_Lilac.Mati_OrangeF_Body",
    "CD_Skins_Psycho_Lilac.Mati_OrangeF_Head",
    "CD_Skins_Psycho_Lilac.Mati_OrangeG_Body",
    "CD_Skins_Psycho_Lilac.Mati_OrangeG_Head",
    "CD_Skins_Psycho_Lilac.Mati_OrangeH_Body",
    "CD_Skins_Psycho_Lilac.Mati_OrangeH_Head",
    "CD_Skins_Psycho_Lilac.Mati_PinkA_Body",
    "CD_Skins_Psycho_Lilac.Mati_PinkA_Head",
    "CD_Skins_Psycho_Lilac.Mati_PinkB_Body",
    "CD_Skins_Psycho_Lilac.Mati_PinkB_Head",
    "CD_Skins_Psycho_Lilac.Mati_PinkC_Body",
    "CD_Skins_Psycho_Lilac.Mati_PinkC_Head",
    "CD_Skins_Psycho_Lilac.Mati_PinkD_Body",
    "CD_Skins_Psycho_Lilac.Mati_PinkD_Head",
    "CD_Skins_Psycho_Lilac.Mati_PurpleA_Body",
    "CD_Skins_Psycho_Lilac.Mati_PurpleA_Head",
    "CD_Skins_Psycho_Lilac.Mati_PurpleB_Body",
    "CD_Skins_Psycho_Lilac.Mati_PurpleB_Head",
    "CD_Skins_Psycho_Lilac.Mati_PurpleC_Body",
    "CD_Skins_Psycho_Lilac.Mati_PurpleC_Head",
    "CD_Skins_Psycho_Lilac.Mati_PurpleD_Body",
    "CD_Skins_Psycho_Lilac.Mati_PurpleD_Head",
    "CD_Skins_Psycho_Lilac.Mati_RedA_Body",
    "CD_Skins_Psycho_Lilac.Mati_RedA_Head",
    "CD_Skins_Psycho_Lilac.Mati_RedB_Body",
    "CD_Skins_Psycho_Lilac.Mati_RedB_Head",
    "CD_Skins_Psycho_Lilac.Mati_RedC_Body",
    "CD_Skins_Psycho_Lilac.Mati_RedC_Head",
    "CD_Skins_Psycho_Lilac.Mati_RedD_Body",
    "CD_Skins_Psycho_Lilac.Mati_RedD_Head",
    "CD_Skins_Psycho_Lilac.Mati_RedE_Body",
    "CD_Skins_Psycho_Lilac.Mati_RedE_Head",
    "CD_Skins_Psycho_Lilac.Mati_RedF_Body",
    "CD_Skins_Psycho_Lilac.Mati_RedF_Head",
    "CD_Skins_Psycho_Lilac.Mati_RedG_Body",
    "CD_Skins_Psycho_Lilac.Mati_RedG_Head",
    "CD_Skins_Psycho_Lilac.Mati_RedH_Body",
    "CD_Skins_Psycho_Lilac.Mati_RedH_Head",
    "CD_Skins_Psycho_Lilac.Mati_TedioreA_Body",
    "CD_Skins_Psycho_Lilac.Mati_TedioreA_Head",
    "CD_Skins_Psycho_Lilac.Mati_TedioreB_Body",
    "CD_Skins_Psycho_Lilac.Mati_TedioreB_Head",
    "CD_Skins_Psycho_Lilac.Mati_TedioreC_Body",
    "CD_Skins_Psycho_Lilac.Mati_TedioreC_Head",
    "CD_Skins_Psycho_Lilac.Mati_TorgueA_Body",
    "CD_Skins_Psycho_Lilac.Mati_TorgueA_Head",
    "CD_Skins_Psycho_Lilac.Mati_TorgueB_Body",
    "CD_Skins_Psycho_Lilac.Mati_TorgueB_Head",
    "CD_Skins_Psycho_Lilac.Mati_TorgueC_Body",
    "CD_Skins_Psycho_Lilac.Mati_TorgueC_Head",
    "CD_Skins_Psycho_Lilac.Mati_Tribal_Body",
    "CD_Skins_Psycho_Lilac.Mati_Tribal_Head",
    "CD_Skins_Psycho_Lilac.Mati_VladofA_Body",
    "CD_Skins_Psycho_Lilac.Mati_VladofA_Head",
    "CD_Skins_Psycho_Lilac.Mati_VladofB_Body",
    "CD_Skins_Psycho_Lilac.Mati_VladofB_Head",
    "CD_Skins_Psycho_Lilac.Mati_VladofC_Body",
    "CD_Skins_Psycho_Lilac.Mati_VladofC_Head",
    "CD_Skins_Psycho_Lilac.Mati_WhiteA_Body",
    "CD_Skins_Psycho_Lilac.Mati_WhiteA_Head",
    "CD_Skins_Psycho_Lilac.Mati_YellowA_Body",
    "CD_Skins_Psycho_Lilac.Mati_YellowA_Head",
    "CD_Skins_Psycho_Lilac.Mati_YellowB_Body",
    "CD_Skins_Psycho_Lilac.Mati_YellowB_Head",
    "CD_Skins_Psycho_Lilac.Mati_YellowC_Body",
    "CD_Skins_Psycho_Lilac.Mati_YellowC_Head",
    "CD_Skins_Psycho_Lilac.Mati_YellowD_Body",
    "CD_Skins_Psycho_Lilac.Mati_YellowD_Head",
    "CD_Skins_Psycho_Lilac.Mati_YellowE_Body",
    "CD_Skins_Psycho_Lilac.Mati_YellowE_Head",
    "CD_Skins_Psycho_Lilac.Mati_YellowF_Body",
    "CD_Skins_Psycho_Lilac.Mati_YellowF_Head",
    "CD_Skins_Psycho_Lilac.Mati_YellowG_Body",
    "CD_Skins_Psycho_Lilac.Mati_YellowG_Head",
    "CD_Skins_Psycho_Lilac.Mati_YellowH_Body",
    "CD_Skins_Psycho_Lilac.Mati_YellowH_Head",
    "Lilac_Char_Psycho.Materials.Mati_PsychoArms",
    "Lilac_Char_Psycho.Materials.Mati_PsychoBody",
    "Lilac_Char_Psycho.Materials.Mati_PsychoHead",
)

CUSTOMIZATIONS = (
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho001",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho002",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho003",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho004",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho005",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho006",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho007",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho008",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho009",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho010",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho011",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho012",
    "GD_AllCustoms_Lilac.Psycho.Head_PsychoJack",
    "GD_AllCustoms_Lilac.Psycho.Head_PsychoMC",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho_DLC1",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho_DLC2",
    "GD_AllCustoms_Lilac.Psycho.Head_Psycho_DLC3",
    "GD_AllCustoms_Lilac.Psycho.Skin_BanditA",
    "GD_AllCustoms_Lilac.Psycho.Skin_BanditB",
    "GD_AllCustoms_Lilac.Psycho.Skin_BanditC",
    "GD_AllCustoms_Lilac.Psycho.Skin_BlackA",
    "GD_AllCustoms_Lilac.Psycho.Skin_BlueA",
    "GD_AllCustoms_Lilac.Psycho.Skin_BlueB",
    "GD_AllCustoms_Lilac.Psycho.Skin_BlueC",
    "GD_AllCustoms_Lilac.Psycho.Skin_BlueD",
    "GD_AllCustoms_Lilac.Psycho.Skin_BlueE",
    "GD_AllCustoms_Lilac.Psycho.Skin_BlueF",
    "GD_AllCustoms_Lilac.Psycho.Skin_BlueG",
    "GD_AllCustoms_Lilac.Psycho.Skin_BlueH",
    "GD_AllCustoms_Lilac.Psycho.Skin_CyanA",
    "GD_AllCustoms_Lilac.Psycho.Skin_CyanB",
    "GD_AllCustoms_Lilac.Psycho.Skin_CyanC",
    "GD_AllCustoms_Lilac.Psycho.Skin_CyanD",
    "GD_AllCustoms_Lilac.Psycho.Skin_CyanE",
    "GD_AllCustoms_Lilac.Psycho.Skin_CyanF",
    "GD_AllCustoms_Lilac.Psycho.Skin_CyanG",
    "GD_AllCustoms_Lilac.Psycho.Skin_CyanH",
    "GD_AllCustoms_Lilac.Psycho.Skin_DahlA",
    "GD_AllCustoms_Lilac.Psycho.Skin_DahlB",
    "GD_AllCustoms_Lilac.Psycho.Skin_DahlC",
    "GD_AllCustoms_Lilac.Psycho.Skin_Gearbox",
    "GD_AllCustoms_Lilac.Psycho.Skin_GrayA",
    "GD_AllCustoms_Lilac.Psycho.Skin_GreenA",
    "GD_AllCustoms_Lilac.Psycho.Skin_GreenB",
    "GD_AllCustoms_Lilac.Psycho.Skin_GreenC",
    "GD_AllCustoms_Lilac.Psycho.Skin_GreenD",
    "GD_AllCustoms_Lilac.Psycho.Skin_GreenE",
    "GD_AllCustoms_Lilac.Psycho.Skin_GreenF",
    "GD_AllCustoms_Lilac.Psycho.Skin_GreenG",
    "GD_AllCustoms_Lilac.Psycho.Skin_GreenH",
    "GD_AllCustoms_Lilac.Psycho.Skin_HyperionA",
    "GD_AllCustoms_Lilac.Psycho.Skin_HyperionB",
    "GD_AllCustoms_Lilac.Psycho.Skin_HyperionC",
    "GD_AllCustoms_Lilac.Psycho.Skin_JakobsA",
    "GD_AllCustoms_Lilac.Psycho.Skin_JakobsB",
    "GD_AllCustoms_Lilac.Psycho.Skin_JakobsC",
    "GD_AllCustoms_Lilac.Psycho.Skin_MaliwanA",
    "GD_AllCustoms_Lilac.Psycho.Skin_MaliwanB",
    "GD_AllCustoms_Lilac.Psycho.Skin_MaliwanC",
    "GD_AllCustoms_Lilac.Psycho.Skin_Minecraft",
    "GD_AllCustoms_Lilac.Psycho.Skin_OrangeA",
    "GD_AllCustoms_Lilac.Psycho.Skin_OrangeB",
    "GD_AllCustoms_Lilac.Psycho.Skin_OrangeC",
    "GD_AllCustoms_Lilac.Psycho.Skin_OrangeD",
    "GD_AllCustoms_Lilac.Psycho.Skin_OrangeE",
    "GD_AllCustoms_Lilac.Psycho.Skin_OrangeF",
    "GD_AllCustoms_Lilac.Psycho.Skin_OrangeG",
    "GD_AllCustoms_Lilac.Psycho.Skin_OrangeH",
    "GD_AllCustoms_Lilac.Psycho.Skin_PinkA",
    "GD_AllCustoms_Lilac.Psycho.Skin_PinkB",
    "GD_AllCustoms_Lilac.Psycho.Skin_PinkC",
    "GD_AllCustoms_Lilac.Psycho.Skin_PinkD",
    "GD_AllCustoms_Lilac.Psycho.Skin_PurpleA",
    "GD_AllCustoms_Lilac.Psycho.Skin_PurpleB",
    "GD_AllCustoms_Lilac.Psycho.Skin_PurpleC",
    "GD_AllCustoms_Lilac.Psycho.Skin_PurpleD",
    "GD_AllCustoms_Lilac.Psycho.Skin_RedA",
    "GD_AllCustoms_Lilac.Psycho.Skin_RedB",
    "GD_AllCustoms_Lilac.Psycho.Skin_RedC",
    "GD_AllCustoms_Lilac.Psycho.Skin_RedD",
    "GD_AllCustoms_Lilac.Psycho.Skin_RedE",
    "GD_AllCustoms_Lilac.Psycho.Skin_RedF",
    "GD_AllCustoms_Lilac.Psycho.Skin_RedG",
    "GD_AllCustoms_Lilac.Psycho.Skin_RedH",
    "GD_AllCustoms_Lilac.Psycho.Skin_TedioreA",
    "GD_AllCustoms_Lilac.Psycho.Skin_TedioreB",
    "GD_AllCustoms_Lilac.Psycho.Skin_TedioreC",
    "GD_AllCustoms_Lilac.Psycho.Skin_TorgueA",
    "GD_AllCustoms_Lilac.Psycho.Skin_TorgueB",
    "GD_AllCustoms_Lilac.Psycho.Skin_TorgueC",
    "GD_AllCustoms_Lilac.Psycho.Skin_Tribal",
    "GD_AllCustoms_Lilac.Psycho.Skin_VladofA",
    "GD_AllCustoms_Lilac.Psycho.Skin_VladofB",
    "GD_AllCustoms_Lilac.Psycho.Skin_VladofC",
    "GD_AllCustoms_Lilac.Psycho.Skin_WhiteA",
    "GD_AllCustoms_Lilac.Psycho.Skin_YellowA",
    "GD_AllCustoms_Lilac.Psycho.Skin_YellowB",
    "GD_AllCustoms_Lilac.Psycho.Skin_YellowC",
    "GD_AllCustoms_Lilac.Psycho.Skin_YellowD",
    "GD_AllCustoms_Lilac.Psycho.Skin_YellowE",
    "GD_AllCustoms_Lilac.Psycho.Skin_YellowF",
    "GD_AllCustoms_Lilac.Psycho.Skin_YellowG",
    "GD_AllCustoms_Lilac.Psycho.Skin_YellowH",
    "GD_DefaultCustoms_Lilac.Psycho.Head_Default",
    "GD_DefaultCustoms_Lilac.Psycho.Skin_Default",
)

SCREEN_PARTICLE_BEHAVIORS = (
    "GD_Lilac_SkillsBase.ActionSkill.ActionSkill_BuzzaxeBarrage.BehaviorProviderDefinition_0.Behavior_ScreenParticle_0",
    "GD_Lilac_SkillsBase.ActionSkill.ActionSkill_BuzzaxeBarrage.BehaviorProviderDefinition_0.Behavior_ScreenParticle_1",
    "GD_Lilac_SkillsBase.ActionSkill.ActionSkill_BuzzaxeBarrage.BehaviorProviderDefinition_0.Behavior_ScreenParticle_2",
    "GD_Lilac_SkillsBase.ActionSkill.Skill_Psycho.BehaviorProviderDefinition_0.Behavior_ScreenParticle_7",
    "GD_Lilac_Skills_Mania.Skills.SilenceTheVoices.BehaviorProviderDefinition_14.Behavior_ScreenParticle_106",
    "GD_Lilac_Skills_Mania.Skills.SilenceTheVoices.BehaviorProviderDefinition_14.Behavior_ScreenParticle_107",
    "GD_Lilac_Skills_Mania.Skills.SilenceTheVoices.BehaviorProviderDefinition_14.Behavior_ScreenParticle_108",
    "GD_Lilac_Skills_Mania.Skills.SilenceTheVoices.BehaviorProviderDefinition_14.Behavior_ScreenParticle_109",
)


# Krieg's heads and skins from the other Borderlands 2 DLCs (holiday, Headhunter, Collector's
# Edition, loot chest, community day...). Definitions are created at runtime from these values.
# (name, Head/Skin, display name, package, data name, primary sort, secondary sort)
EXTRA_CUSTOMIZATIONS = (
    ('Head_Snowman', 'Head', "I'M MELTIIIING", 'CD_Psycho_Head_Snowman', 'Snowman', 27, 0),
    ('Head_Turkey', 'Head', 'I AM DELICIOUS', 'CD_Psycho_Head_Turkey', 'Turkey', 27, 1),
    ('Skin_Thanks', 'Skin', 'PAINUCOPIA', 'CD_Psycho_Skin_Thanks', 'Thanks', 26, 1),
    ('Skin_Xmas', 'Skin', 'WARM AND TOASTY', 'CD_Psycho_Skin_Xmas', 'Xmas', 26, 0),
    ('Head_PsychHaz', 'Head', 'BREATHE IT IN YOUR BONES', 'CD_Psycho_Head_PsychHaz', 'PsychHaz', 18, 0),
    ('Skin_PsychAne', 'Skin', 'MY BLISTERS HAVE BLISTERS', 'CD_Psycho_Skin_PsychAne', 'PsychAne', 21, 0),
    ('Head_PsychoAster', 'Head', 'MY EARS ARE RINGING', 'CD_Psycho_Head_PsychoAster', 'PsychoAster', 20, 0),
    ('Skin_PsychoAster', 'Skin', 'MY FANTASIES INVOLVE BLOOD', 'CD_Psycho_Skin_PsychoAster', 'PsychoAster', 22, 0),
    ('Head_PsychoCD', 'Head', 'REACH FOR THE SKIS', 'CD_Psycho_Head_PsychoCD', 'PsychoCD', 24, 0),
    ('Skin_PsychoCD', 'Skin', 'HOW DO I VESTS', 'CD_Psycho_Skin_PsychoCD', 'PsychoCD', 25, 0),
    ('Head_Pumpkin', 'Head', 'MY HEAD IS NOW A PUMPKIN', 'CD_Psycho_Head_Pumpkin', 'Pumpkin', 26, 0),
    ('Skin_Frank', 'Skin', 'TRICKS ARE TREATS', 'CD_Psycho_Skin_Frank', 'Frank', 25, 0),
    ('Head_PsychoHP04', 'Head', 'BREATHE DEEP', 'CD_Psycho_Head_PsychoHP04', 'PsychoHP04', 21, 0),
    ('Head_PsychoHP04B', 'Head', 'I WANNA BE WANTED', 'CD_Psycho_Head_PsychoHP04B', 'PsychoHP04B', 21, 0),
    ('Head_PsychoHP04C', 'Head', 'SPLITTING HEADACHE HAHAHA', 'CD_Psycho_Head_PsychoHP04C', 'PsychoHP04C', 21, 0),
    ('Head_PsychoHP04D', 'Head', 'MY AXE IS THIRSTY', 'CD_Psycho_Head_PsychoHP04D', 'PsychoHP04D', 21, 0),
    ('Skin_PsychoHP04', 'Skin', 'THE DARK LEAKS OUTTA ME', 'CD_Psycho_Skin_PsychoHP04', 'PsychoHP04', 22, 0),
    ('Skin_PsychoHP04B', 'Skin', "I'LL NEVER GO BACK", 'CD_Psycho_Skin_PsychoHP04B', 'PsychoHP04B', 22, 0),
    ('Skin_PsychoHP04C', 'Skin', 'CROSSED THE LINE', 'CD_Psycho_Skin_PsychoHP04C', 'PsychoHP04C', 22, 0),
    ('Skin_PsychoHP04D', 'Skin', 'BATHE IN THE GORE', 'CD_Psycho_Skin_PsychoHP04D', 'PsychoHP04D', 22, 0),
    ('Head_PsychoHP05', 'Head', 'GLUG GLUG GLUG', 'CD_Psycho_Head_PsychoHP05', 'PsychoHP05', 24, 0),
    ('Skin_PsychoHP05', 'Skin', 'DRINK IT DOWN', 'CD_Psycho_Skin_PsychoHP05', 'PsychoHP05', 25, 0),
    ('Head_Lobelia', 'Head', 'WEAR YOUR TORSO LIKE A HAT', 'CD_Psycho_Head_Lobelia', 'Lobelia', 23, 0),
    ('Skin_Lobelia', 'Skin', 'LORD OF MEAT', 'CD_Psycho_Skin_Lobelia', 'Lobelia', 24, 0),
    ('Head_LootChest2', 'Head', 'GOLIATH', 'CD_Psycho_Head_LootChest2', 'LootChest2', 19, 0),
    ('Head_PsychoEaster', 'Head', 'AM I PRETTY NOW', 'CD_Psycho_Head_PsychoEaster', 'PsychoEaster', 29, 0),
    ('Head_PsychoVday', 'Head', 'BONE DADDYYYYY', 'CD_Psycho_Head_PsychoVday', 'PsychoVday', 29, 1),
    ('Skin_PsychoEaster', 'Skin', 'BEEN WORKING ON MY TAN', 'CD_Psycho_Skin_PsychoEaster', 'PsychoEaster', 28, 0),
    ('Skin_PsychoVday', 'Skin', "I'LL TEAR YOUR LEAVES OFF", 'CD_Psycho_Skin_PsychoVday', 'PsychoVday', 28, 1),
    ('Head_PsychoPeony', 'Head', 'PUT A SHANK INTO BOBBY', 'CD_Psycho_Head_PsychoPeony', 'PsychoPeony', 31, 0),
    ('Skin_PsychoPeony', 'Skin', 'PICK THE SCAV', 'CD_Psycho_Skin_PsychoPeony', 'PsychoPeony', 30, 0),
)

# Material instances in those packages (same treatment as MATERIAL_INSTANCES).
EXTRA_MATERIAL_INSTANCES = (
    'CD_Heads_Psycho_Anemone.Materials.Mati_PsychHaz',
    'CD_Heads_Psycho_Aster.Materials.Mati_PsychoAster',
    'CD_Heads_Psycho_CommDay2013.Mati_PsychoCD',
    'CD_Heads_Psycho_Gardenia04.Materials.Mati_PsychoHP04',
    'CD_Heads_Psycho_Gardenia04.Materials.Mati_PsychoHP04c',
    'CD_Heads_Psycho_Gardenia04.Materials.Mati_PsychoHP04d',
    'CD_Heads_Psycho_Gardenia04.Materials.PsychoHP04b',
    'CD_Heads_Psycho_Gardenia05.Materials.Mati_PsychoHP05',
    'CD_Heads_Psycho_LootChest2.Materials.Mati_PsychoGoliath',
    'CD_Heads_Psycho_Nasturtium.Materials.Mati_PsychoEaster',
    'CD_Heads_Psycho_Nasturtium.Materials.Mati_PsychoVday',
    'CD_Heads_Psycho_Peony.Materials.Mati_PsychoPeony_Head',
    'CD_Heads_Psycho_allium.Materials.Mati_PsychoTurkey',
    'CD_Heads_Psycho_allium.Materials.Mati_Snowman',
    'CD_Heads_Psycho_flax.Materials.Mati_Pumpkin',
    'CD_Skins_Psycho_Anemone.Materials.Mati_PsychAne_Body',
    'CD_Skins_Psycho_Anemone.Materials.Mati_PsychAne_Head',
    'CD_Skins_Psycho_Aster.Materials.Mati_PsychoAster_Body',
    'CD_Skins_Psycho_Aster.Materials.Mati_PsychoAster_Head',
    'CD_Skins_Psycho_CommDay2013.Materials.Mati_PsychoCD_Body',
    'CD_Skins_Psycho_CommDay2013.Materials.Mati_PsychoCD_Head',
    'CD_Skins_Psycho_Gardenia04.Materials.Mati_PsychoHP04B_Body',
    'CD_Skins_Psycho_Gardenia04.Materials.Mati_PsychoHP04B_Head',
    'CD_Skins_Psycho_Gardenia04.Materials.Mati_PsychoHP04C_Body',
    'CD_Skins_Psycho_Gardenia04.Materials.Mati_PsychoHP04C_Head',
    'CD_Skins_Psycho_Gardenia04.Materials.Mati_PsychoHP04D_Body',
    'CD_Skins_Psycho_Gardenia04.Materials.Mati_PsychoHP04D_Head',
    'CD_Skins_Psycho_Gardenia04.Materials.Mati_PsychoHP04_Body',
    'CD_Skins_Psycho_Gardenia04.Materials.Mati_PsychoHP04_Head',
    'CD_Skins_Psycho_Gardenia05.Materials.Mati_PsychoHP05_Body',
    'CD_Skins_Psycho_Gardenia05.Materials.Mati_PsychoHP05_Head',
    'CD_Skins_Psycho_Lobelia.Materials.Mati_Lobelia_Body',
    'CD_Skins_Psycho_Lobelia.Materials.Mati_Lobelia_Head',
    'CD_Skins_Psycho_Peony.Materials.Mati_PsychoPeony_Body',
    'CD_Skins_Psycho_Peony.Materials.Mati_PsychoPeony_Head',
    'CD_Skins_Psycho_allium.Materials.Mati_Thanks_Body',
    'CD_Skins_Psycho_allium.Materials.Mati_Thanks_Head',
    'CD_Skins_Psycho_allium.Materials.Mati_Xmas_Body',
    'CD_Skins_Psycho_allium.Materials.Mati_Xmas_Head',
    'CD_Skins_Psycho_flax.Mati_Frank_Body',
    'CD_Skins_Psycho_flax.Mati_Frank_Head',
    'CD_Skins_Psycho_nasturtium.Materials.Mati_PsychoEaster_Body',
    'CD_Skins_Psycho_nasturtium.Materials.Mati_PsychoEaster_Head',
    'CD_Skins_Psycho_nasturtium.Materials.Mati_PsychoVday_Body',
    'CD_Skins_Psycho_nasturtium.Materials.Mati_PsychoVday_Head',
)
